import { Meta, Story } from '@storybook/react';
import { Statistics, StatisticsProps } from './Statistics';

export default {
  title: 'Component/Statistics',
  component: Statistics,
} as Meta;

// const descriptionItems =

const Template: Story<StatisticsProps> = () => {
  return (
    <Statistics
      title='Lorem ipsum dolor'
      image={''}
      descriptionTitle='77 million'
      descriptionDetail=' new blog comments are generated by readers each month.'
    />
  );
};

export const StatisticsExample = Template.bind({});
